### PR TITLE
Integrated cycles

### PR DESCRIPTION
**Pull request by 01Parzival10**
Described in #210

### CODE REVIEW

**Comment by 01Parzival10** [comment]
DataFlowAnalalysis/ExampleModels#13 has to be merged first

**Comment by uuqjz** [comment]
Is picking any node for cyclic sinks semantically right?

**Review by Nicolas-Boltz — COMMENTED** [review]
I would suggest that @BenjaminArp and @uuqjz review this PR as they are the ones most familiar with the cycle finding. 
For me it looks good.

**Comment by Nicolas-Boltz** [comment]
> Is picking any node for cyclic sinks semantically right?

could you maybe elaborate a little bit more? I do not see a spot where a random node ist chosen and the code on first glance looks more or less similar to the previous code of the cyclic finder?

**Comment by uuqjz** [comment]
> @uuqjz Could you maybe elaborate a little bit more? I do not see a spot where a random node ist chosen and the code on first glance looks more or less similar to the previous code of the cyclic finder?

This commit `Fix: In case of cycle without entry or exit pick any node as sink` introduced that.

**Comment by 01Parzival10** [comment]
> Is picking any node for cyclic sinks semantically right?

No. I just realized the issue with the example model of the WebEditor, since right now the converter behavior is adding all Pins as Input pins on set actions (something I'd change). This at least allows a TFG to be created at all, otherwise no sink is picked.

Correctly one would have to identify the node in the cycle that "starts" the cycle by sending out a label and use that as sink (only when theres no flow going out of the cycle)

**Comment by 01Parzival10** [comment]
^^ This has not been done before tho, and I fear a lot of computational complexity

**Comment by 01Parzival10** [comment]
For the moment i suggest we disallow terminal cycles (they didnt work before either). Finding a sink in a single cycle is not too difficult but for handling multiple or nested cycles i would have to build an almost complete reverse TFG

**Comment by 01Parzival10** [comment]
> Is picking any node for cyclic sinks semantically right?

I described the problem in #214

**Pull request merged**
