### PR TITLE
Add Unified Logging for PCM and DFD Analyses

### LINKED ISSUE #126: Unify log output
Currently, we use different formats for the log output of the DFD and PCM analysis, which should be unified (probably to the DFD log output).

PCM analysis:
```
Successfully initialized standalone log4j for the data flow analysis.
Successfully initialized standalone environment for the data flow analysis.
Successfully initialized standalone data flow analysis.
```

DFD analysis:
```
0    [main] INFO  ysis.dfd.DFDConfidentialityAnalysis  - Successfully initialized standalone environment for the data flow analysis.
396  [main] INFO  lysis.core.UncertaintySourceManager  - Started validating uncertainty sources.
```

### PR DESCRIPTION
**Pull request by Entenwilli**
> [!IMPORTANT] 
> This PR is dependent on #123 and thus needs to be merged afterwards

This PR adds unified logging for both analyses in this repo. The proposed logging format is:
```
Timestamp [Level] Classname - Message
```
An example would be:
```
12 [INFO] PCMConfidentialityAnalysis - Loaded model elements from files
```
This PR closes #126

### CODE REVIEW

**Comment by sebinside** [comment]
#123 has been merged, @Entenwilli please rebase this PR so we can also merge it

**Comment by Entenwilli** [comment]
@sebinside This branch is now fully up-to-date

**Review by sebinside — COMMENTED** [review]
Would it be possible to move the common code of the DFD analysis and the PCM analysis to the abstract parent class?

**Comment by Entenwilli** [comment]
Yep, this is (now) implemented in 6f6e383a3b99d4cfe9a2facdc68993beafe544dd

**Pull request merged**
