### PR TITLE
Fixing emtpy assignment issue

### PR DESCRIPTION
**Pull request by 01Parzival10**
@uuqjz You added an assignment template which was never removed in case of an empty output pin list

### CODE REVIEW

**Comment by uuqjz** [comment]
Wouldnt it be easier to pull `behaviour.getAssignment().remove(template);` out of the if so its executed everytime?

**Comment by uuqjz** [comment]
Could you add a test (or just an assert in one of the existing tests) that checks the amount of assignment against the amount of outpins?

**Comment by uuqjz** [comment]
> Are they necessarily equal?

MicroSecEnd doesnt have pins, just flows between nodes.
Therefore there should be as many assignment as flows in the micro model, right?

**Comment by uuqjz** [comment]
Ive added a test, please check whether it is to your liking and would fail without the fix.

**Review by sebinside — APPROVED** [review]
LGNTM

**Pull request merged**
